version: 2.1
executors:
    texture_exec:
        macos:
            xcode: 10.1.0
        working_directory: ~/project
commands:
    buildsh:
        parameters:
            mode: {type: string}
        steps:
            # - {attach_workspace: {at: ~/project}}
            - {run: {name: 'Fetch cocoapods spec repo from cache', command: "curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf\n"}}
            - {run: xcrun simctl list}
            - {run: './build-new.sh << parameters.mode >>'}
jobs:
    fetch_deps:
        executor: texture_exec
        steps:
            - checkout
            # - {attach_workspace: {at: ~/project}}
            # - {run: {name: 'Fetch cocoapods spec repo from cache', command: "curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf\n"}}
            # - {persist_to_workspace: {root: ., paths: .}}
    tests:
        executor: texture_exec
        steps:
            - {buildsh: {mode: tests}}
    examples-pt1:
        executor: texture_exec
        steps:
            - {buildsh: {mode: examples-pt1}}
    examples-pt2:
        executor: texture_exec
        steps:
            - {buildsh: {mode: examples-pt2}}
    examples-pt3:
        executor: texture_exec
        steps:
            - {buildsh: {mode: examples-pt3}}
    examples-extra:
        executor: texture_exec
        steps:
            - {buildsh: {mode: examples-extra}}
    life-without-cocoapods:
        executor: texture_exec
        steps:
            - {buildsh: {mode: life-without-cocoapods}}
    cocoapods-lint:
        executor: texture_exec
        steps:
            - {buildsh: {mode: cocoapods-lint}}
    carthage:
        executor: texture_exec
        steps:
            - {buildsh: {mode: carthage}}
workflows:
    version: 2.1
    github_pr_check:
        jobs:
            - fetch_deps
            - {tests: {requires: [fetch_deps]}}
            - {examples-pt1: {requires: [tests]}}
            - {examples-pt2: {requires: [tests]}}
            - {examples-pt3: {requires: [tests]}}
            - {examples-extra: {requires: [tests]}}
            - {life-without-cocoapods: {requires: [tests]}}
            - {carthage: {requires: [tests]}}
            - {cocoapods-lint: {requires: [tests], filters: {branches: {only: master}}}}
